#!name=Cookie
#!desc=该模块适用于定时签到脚本的Cookie获取. 您可以在使用后手动将其禁用，以免产生不必要的MITM.
#!system=ios


[Script]

# > 京东
# 浏览器登录 https://bean.m.jd.com 点击签到并且出现签到日历
JD_DailyBonus.js = max-size=0,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js,type=http-request,pattern=https:\/\/api\.m\.jd\.com\/client\.action.*functionId=signBean(Index|GroupStageIndex)
# > 百度贴吧
tieba.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/tieba/tieba.cookie.js,type=http-request,pattern=^https?:\/\/tieba\.baidu\.com\/?.?
# > 爱奇艺
iQIYI_GetCookie.js = script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/iQIYI-DailyBonus/iQIYI_GetCookie.js,type=http-request,pattern=https?:\/\/.*\.iqiyi\.com\/.*authcookie=
# > 吾爱破解
Get-Cookie.js = script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/52pojieDailyBonus/Get-Cookie.js,type=http-request,pattern=https:\/\/www\.52pojie\.cn\/home\.php\?
# Chavyleung
# > 百度贴吧
# 用浏览器访问并登录: https://tieba.baidu.com 或者 https://tieba.baidu.com/index/
tieba.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/tieba/tieba.cookie.js,type=http-request,pattern=^https?:\/\/tieba\.baidu\.com\/?.?
# > 网易云音乐
# 浏览器访问并登录: https://music.163.com/m/login
neteasemusic.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/neteasemusic.cookie.js,type=http-request,pattern=^https?:\/\/music\.163\.com\/?.?
# > 哔哩哔哩
# 浏览器访问并登录: https://www.bilibili.com 或 https://live.bilibili.com 系统提示:获取Cookie: 成功
bilibili.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/bilibili/bilibili.cookie.js,type=http-request,pattern=^https:\/\/(www|live)\.bilibili\.com\/?.?
# > 威锋论坛
feng.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/feng/feng.cookie.js,type=http-request,pattern=^https:\/\/(www\.)?feng\.com\/?.?
# > 腾讯视频
# 手机浏览器访问并登录下https://film.qq.com/,随便选 1 部电影观看
videoqq.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/videoqq/videoqq.cookie.js,type=http-request,pattern=^https:\/\/access.video.qq.com\/user\/auth_refresh
# > 字幕组
zimuzu.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/zimuzu/zimuzu.cookie.js,type=http-request,pattern=^https?:\/\/(www\.)?rrys2019\.com\/?.?
zimuzu.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/zimuzu/zimuzu.cookie.js,type=http-request,pattern=^http:\/\/ios.zmzapi.com\/index.php.*a=(mobile_)?login
# > 人人视频
rrtv.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/rrtv/rrtv.cookie.js,type=http-request,pattern=^https:\/\/api\.rr\.tv\/user\/profile
# > CSDN
csdn.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/csdn/csdn.cookie.js,type=http-request,pattern=^https:\/\/passport.csdn.net\/v2\/api\/app\/login\/checkAndRefreshToken
csdn.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/csdn/csdn.cookie.js,type=http-request,pattern=^https:\/\/gw.csdn.net\/mini-app\/v2\/lucky_draw\/login\/sign_in\?
# > 美团
meituan.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.cookie.js,requires-body=true,type=http-request,pattern=^https:\/\/i.meituan.com\/evolve\/signin\/signpost\/
# > WPS
wps.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/wps/wps.cookie.js,type=http-request,pattern=^https:\/\/zt.wps.cn\/2018\/ldocer_check_in\/api\/act_list
wps.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/wps/wps.cookie.js,type=http-request,pattern=^https:\/\/zt.wps.cn\/2018\/clock_in\/api\/sign_up
# > 腾讯新闻 (By 红鲤鱼与绿鲤鱼与驴)
Tengxunnews.js = script-path=https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Task/Tengxunnews.js,type=http-request,pattern=http:\/\/mtrace\.qq\.com\/mkvcollect*



[MITM]
hostname = %APPEND% api.m.jd.com, music.163.com, *.iqiyi.com, www.52pojie.cn, *.bilibili.com, *.feng.com, *.video.qq.com, *.rrys2019.com, *.rr.tv, h5.ele.me, *.m.163.com, ios.zmzapi.com, *.y.qq.com, *.csdn.net, mtrace.qq.com, i.meituan.com, node.kg.qq.com, zt.wps.cn, tieba.baidu.com,