#!name=签到定时脚本
#!desc=该模块适用于定时签到，建议本地安装以便自定义修改签到时间。
#!system=ios


[Script]

# > 京东
JD_DailyBonus.js = type=cron,cronexp=0 0 0 * * *,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js,script-update-interval=0
# > 爱奇艺
iQIYI_DailyBonus.js = type=cron,cronexp=5 0 0 * * *,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/iQIYI-DailyBonus/iQIYI_DailyBonus.js,script-update-interval=0
# > 吾爱破解
52pojie.js = type=cron,cronexp=10 0 0 * * *,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/52pojieDailyBonus/52pojie.js,script-update-interval=0
# > 哔哩哔哩漫画
Manga.js = type=cron,cronexp=15 0 0 * *,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Bilibili-DailyBonus/Manga.js,script-update-interval=0

# bilibili
# 打开浏览器访问: https://www.bilibili.com 或 https://live.bilibili.com
bilibili.js = type=cron,cronexp=35 0 0 * * *,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/bilibili/bilibili.js,script-update-interval=0
# 如需银瓜子转硬币，取消下方注释
bilibili.silver2coin.js = type=cron,cronexp=40 0 0 * * *,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/bilibili/bilibili.silver2coin.js,script-update-interval=0

# 网易云音乐
# 浏览器访问并登录: https://music.163.com/m/login
neteasemusic.js = type=cron,cronexp=0 1 0 * * *,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/quanx/neteasemusic.js,script-update-interval=0

# 百度签到
# 先登录,浏览器访问一下: https://tieba.baidu.com 或者 https://tieba.baidu.com/index/
tieba.js = type=cron,cronexp="0 0,1,2 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/tieba/tieba.js,script-update-interval=0

# 腾讯视频
# 1.手机浏览器访问并登录: https://film.qq.com/
videoqq.js = type=cron,cronexp=35 1 0 * * *,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/videoqq/videoqq.js,script-update-interval=0

# CSDN
# 打开 APP , 系统提示: `获取刷新链接: 成功`,然后手动签到 1 次, 系统提示: `获取Cookie: 成功`
csdn.js = type=cron,cronexp=0 2 0 * * *,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/csdn/csdn.js,script-update-interval=0

# 美团
# 打开 APP , 然后手动签到 1 次, (`首页` > `红包签到`)
meituan.js = type=cron,cronexp=40 2 0 * * *,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.js,script-update-interval=0


# 腾讯新闻 (By 红鲤鱼与绿鲤鱼与驴)
# 登录app 签到
Tengxunnews.js = type=cron,cronexp=55 4 0 * * *,script-path=https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Task/Tengxunnews.js,script-update-interval=0



